# In case of getting certs from splunk server
- name: Get Splunk Certs
  shell: aws secretsmanager get-secret-value --secret-id THESECRET --region us-east-1 | jq ".SecretString" | sed 's/\\n //g; s/\ \n//g; s/\\"/"/g; s/"\\n/"/g; s/^"//; s/"$//' | jq ".ssl_pass" | sed 's/\"//g'
  register: splunk_ssl_pass
  when: APPLICATION == "sth" and ( ENV == "dev" or ENV == "test" )