---

- name: Download the Splunk package (CentOS)
  get_url:
    url: "{{ splunk_rpm }}"
    dest: "/tmp/{{ splunk_forwarder_rpm }}"
    checksum: "{{ splunk_rpm_checksum }}"
  when: ansible_os_family == "RedHat"

- name: Install Splunk (CentOS)
  yum:
    name: "/tmp/{{ splunk_forwarder_rpm }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Copy inputs file
  template:
    src: "{{ item.src }}"
    dest: 
    backup: yes
    mode: 440
  with_items:
    - {src: 'inputs_dev.conf.j2', dest: '/opt/splunkforwarder/etc/system/local/inputs.conf'}
      {src: 'inputs_test.conf.j2', dest: '/opt/splunkforwarder/etc/system/local/inputs.conf'}
      {src: 'limits.conf', dest: '/opt/splunkforwarder/etc/system/local/inputs.conf'}
  tags: config_copy

- name: Copy outputs file
  template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    backup: yes
    mode: 440
  tags: config_copy

- name: Upload Splunk Systemd Script
  copy:
    src: splunk.service
    dest: /etc/systemd/system/splunkd.service
    owner: 0
    group: 0
    mode: 0755
  when: ansible_service_mgr == 'systemd'

- name: Adding splunk user
  shell: | 
    /opt/splunkforwarder/bin/splunk stop
    echo "[user_info]" > /opt/splunkforwarder/etc/system/local/user-seed.conf
    echo "USERNAME = admin " >> /opt/splunkforwarder/etc/system/local/user-seed.conf
    echo "PASSWORD = changeme " >> /opt/splunkforwarder/etc/system/local/user-seed.conf

- name Enable Splunk Forwarder
  service:
    name: Splunkd
    enabled: yes
    state: started